imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler:
        enabled: true
        collect: true
        only_exceptions: false
        only_master_requests: false
        dsn:      "mysql:host=%database_host%;dbname=%database_name%"
        username: "%database_user%"
        password: "%database_password%"
        lifetime: 3600


web_profiler:
    toolbar: %debug_toolbar%
    intercept_redirects: %debug_redirects%

#monolog:
#    handlers:
#        main:
#            type:   stream
#            path:   "%kernel.logs_dir%/%kernel.environment%.log"
#            level:  debug
#        console:
#            type:   console
#            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
   use_controller: false

#swiftmailer:
#    delivery_address: me@example.com
