imports:
    - { resource: config.yml }

framework:
    profiler:
        enabled: true
        collect: true
        only_exceptions: false
        only_master_requests: false
        dsn:      "mysql:host=%database_host%;dbname=%database_name%"
        username: "%database_user%"
        password: "%database_password%"
        lifetime: 3600

#    validation:
#        cache: apc

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

monolog:
    handlers:
#        type: errorlog
#        level: error
#        syslog:
#            type: syslog
#            level: error
#        main:
#            type:         fingers_crossed
#            action_level: error
#            handler:      nested
#        console:
#            type:  console

        nested:
            type:  stream
            path:  "php://stderr"
            level: debug