## YAML Template.
Xo\GameBundle\Entity\User:
    type: entity
    table: xo_users
    id:
        login:
            type: string
            length: 64
            nullable: false
            generator: { strategy: NONE }
        
    fields:
        
       
        hash:
            type: string
            length: 255
            nullable: false
