start:
    path:     /
    defaults: { _controller:  XoGameBundle:Xo:index }

main:
    path: /{locale}
    defaults: { _controller: XoGameBundle:Xo:main }

signin:
    path: /{locale}/signin
    defaults: { _controller: XoGameBundle:Xo:signin }

signup:
    path: /{locale}/signup
    defaults: { _controller: XoGameBundle:Xo:signup }

invite:
    path: /{locale}/invite
    defaults: { _controller: XoGameBundle:Xo:invite }

cancel:
    path: /{locale}/cancel
    defaults: { _controller: XoGameBundle:Xo:cancel }

accept:
    path: /{locale}/accept
    defaults: { _controller: XoGameBundle:Xo:accept }

decline:
    path: /{locale}/decline
    defaults: { _controller: XoGameBundle:Xo:decline }

keepalive:
    path: /{locale}/keepalive
    defaults: { _controller: XoGameBundle:Xo:keepalive }

makemove:
    path: /{locale}/makemove
    defaults: { _controller: XoGameBundle:Xo:makemove }

leave:
    path: /{locale}/leave
    defaults: { _controller: XoGameBundle:Xo:leave }

replay:
    path: /{locale}/replay
    defaults: { _controller: XoGameBundle:Xo:replay }

accept_replay:
    path: /{locale}/accept_replay
    defaults: { _controller: XoGameBundle:Xo:acceptReplay }

signout:
    path: /{locale}/signout
    defaults: { _controller: XoGameBundle:Xo:signout }

quit_lobby:
    path: /{locale}/quit_lobby
    defaults: { _controller: XoGameBundle:Xo:quitLobby }

quit_board:
    path: /{locale}/quit_board
    defaults: { _controller: XoGameBundle:Xo:quitBoard }
